# Generated by Django 2.0.5 on 2018-06-09 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterModelTable(
            name='sales',
            table='tutorial_product_sales',
        ),
    ]
