# Generated by Django 2.0.5 on 2018-06-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_auto_20180609_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='customer',
        ),
    ]
